//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroEmall.Models
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public class Goods
    {
        public Goods()
        {
            this.StatusId = 503;
        }
    
        public string Id { get; set; }
        public string CategoryId { get; set; }
        public string BrandId { get; set; }
        public string Name { get; set; }
        public double OriginalPrice { get; set; }
        public Nullable<double> PresentPrice { get; set; }
        public string Unit { get; set; }
        public string Desc { get; set; }
        public string Spec { get; set; }
        public string Service { get; set; }
        public int Clicks { get; set; }
        public int Saves { get; set; }
        public int Bonus { get; set; }
        public int GoldPool { get; set; }
        public int StatusId { get; set; }
        public System.DateTime AddDate { get; set; }
        public int Integral { get; set; }
    }
}
