//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroEmall.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WMContext : DbContext
    {
        public WMContext()
            : base("name=WMContext")
        {
            this.Configuration.LazyLoadingEnabled = false;
    		this.Configuration.ProxyCreationEnabled = false;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Goods> Goods { get; set; }
        public DbSet<GoodCategories> GoodCategories { get; set; }
        public DbSet<GoodImages> GoodImages { get; set; }
        public DbSet<Options> Options { get; set; }
        public DbSet<OrderGoods> OrderGoods { get; set; }
        public DbSet<ShopCars> ShopCars { get; set; }
        public DbSet<Users> Users { get; set; }
        public DbSet<UserBonus> UserBonus { get; set; }
        public DbSet<UserClicks> UserClicks { get; set; }
        public DbSet<UserReceipts> UserReceipts { get; set; }
        public DbSet<UserSets> UserSets { get; set; }
        public DbSet<Orders> Orders { get; set; }
        public DbSet<Administartors> Administartors { get; set; }
        public DbSet<UserIntegrals> UserIntegrals { get; set; }
        public DbSet<Regions> Regions { get; set; }
        public DbSet<GoodBrands> GoodBrands { get; set; }
    }
}
