//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroEmall.Models
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public class UserBonus
    {
        public string Id { get; set; }
        public string UserId { get; set; }
        public string OrderId { get; set; }
        public double BonusSum { get; set; }
        public System.DateTime AddDate { get; set; }
    }
}
