//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace MicroEmall.Models
{
    using System;
    using System.Collections.Generic;
    
    [Serializable]
    public class Users
    {
        public Users()
        {
            this.StatusId = 201;
        }
    
        public string Id { get; set; }
        public int RoleId { get; set; }
        public string OpenId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string NickName { get; set; }
        public string Image { get; set; }
        public string Mobile { get; set; }
        public string BankCard { get; set; }
        public int StatusId { get; set; }
        public System.DateTime AddDate { get; set; }
        public int Integral { get; set; }
    }
}
